version: '3.3'

services:
  drupal:
    image: drupal:7.61-apache
    depends_on:
      - mysql
    ports:
      - 3435:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always

  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bingbong
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db_data:/var/lib/mysql
      - ./dev-newrelic.sql:/dev-newrelic.sql
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
